### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kaustubhkulkarni1509**
Should we add the part where we predict the amount of energy which will be created in future depending upon the weather forecast.

### CODE REVIEW

**Review by andrew-selvia — COMMENTED** [review]
@agrawaladit you'll need to review this since it's your proposal. I'll let you determine if it's in scope.

**Comment by agrawaladit** [comment]
@kaustubhkulkarni1509 That's a great idea, but weather forecast is available only for short duration like 14 days. We are aiming at long term decisions like 6-10 years. So instead of forecast we'll need to predict the weather from the past years data available and environmental changes.
But that's a good point I'll add that we'll predict future weather from the past data.

**Comment by kaustubhkulkarni1509** [comment]
@Aditya....That was my point...weather forecast is available for short
period and we will inform the user one day before if the power generation
is low the next day. Review this point. I think we should add this because
it can give more AI flavour to our project.

**Comment by agrawaladit** [comment]
@kaustubhkulkarni1509 Great suggestion! I made the changes to the repo. Take a look and suggest if something else is needed.

**Pull request closed without merging**
